### ISSUE TITLE
German special characters

### ISSUE THREAD

**Issue by Brixy** [larsenwork/Gidole#36]
Thank you very much for this stunningly beautiful font! Looking forward to the italic and other styles.

Just wanted to mention that German special characters are currently not supported. As it is a [DIN variant](https://en.wikipedia.org/wiki/Deutsches_Institut_f%C3%BCr_Normung), I guess this is important ;-)
- ä
- Ä
- ö
- Ö
- ü
- Ü
- ß
- ẞ ([Capital ß](https://en.wikipedia.org/wiki/Capital_%E1%BA%9E)—new and supported by few typefaces so far)

**Comment by larsenwork** [comment]
@Brixy they should all be there, including ẞ - where did you download from?

**Comment by Brixy** [comment]
Thanks @larsenwork!

O sorry, I just tested a webfont version, but do not remeber, where I got it from.

BTW: I also tested umlauts on your Gidole website using a web developer tool, where they are not yet available.

Maybe it would be useful to provide on official webfont kit?

Thank you very much (beautiful ẞ, & and f-ligatures)

**Comment by larsenwork** [comment]
Thanks, they are not on the website because I've subsetted it to only English characters to optimise file size.

I could provide an official we font but you should always subset it for you use case so your users don't download Greek, Cyrillic or (soon) amharic characters of you never use them so I'm unsure about the value and is just one more thing to maintain and update so I'll definitely not do it while actively expanding and improving the font :)

**Comment by Brixy** [comment]
Thank you very much for your detailed answer. I’m slowly getting into the github/open source workflow.

Cheers!

**Comment by larsenwork** [comment]
👍
